<?php

declare(strict_types=1);

namespace Drupal\Tests\agency_operations\Functional;

use Behat\Mink\Driver\BrowserKitDriver;
use Drupal\Tests\BrowserTestBase;
use PHPUnit\Framework\Attributes\RunTestsInSeparateProcesses;

/**
 * Covers access control and the deliberate absence of execution routes.
 *
 * @group agency_operations
 */
#[RunTestsInSeparateProcesses]
final class AgencyOperationsAccessTest extends BrowserTestBase {

  /**
   * {@inheritdoc}
   */
  protected static $modules = [
    'agency_operations',
  ];

  /**
   * {@inheritdoc}
   */
  protected $defaultTheme = 'stark';

  /**
   * Proves V3 is human-first while preserving read-only technical truth.
   */
  public function testPermissionProtectsReadOnlyCockpit(): void {
    $this->drupalGet('/admin/agency/operations');
    $this->assertSession()->statusCodeEquals(403);

    $account = $this->drupalCreateUser(['access agency operations']);
    $this->drupalLogin($account);

    $this->drupalGet('/admin/agency/operations');
    $this->assertSession()->statusCodeEquals(200);
    $this->assertSession()->pageTextContains('Agency Operations');
    $this->assertSession()->pageTextContains('Daily operational overview');
    $this->assertSession()->pageTextContains('Current runtime');
    $this->assertSession()->pageTextContains('Environments');
    $this->assertSession()->pageTextContains('PROD');
    $this->assertSession()->pageTextContains('PREPROD');
    $this->assertSession()->pageTextContains('DEVELOPMENT');
    $this->assertSession()->pageTextContains('Content');
    $this->assertSession()->pageTextContains('PREPROD data');
    $this->assertSession()->pageTextContains('Development data');
    $this->assertSession()->pageTextContains('Recent evidence');
    $this->assertSession()->pageTextContains('Operational');
    $this->assertSession()->pageTextNotContains('Opérationnel');
    $this->assertSession()->pageTextContains('PLAN is preparation and analysis only');
    $this->assertSession()->pageTextContains('APPLY is not available from this cockpit');
    $this->assertSession()->pageTextContains('Technical details');
    $this->assertSession()->elementNotExists('css', 'details[open]');
    $this->assertSession()->elementTextContains('css', 'details', 'CODE_CONFIG');
    $this->assertSession()->elementTextContains('css', 'details', 'Technical status');
    $this->assertSession()->elementTextContains('css', 'details', 'SOURCE_IMPLEMENTED');
    $this->assertSession()->elementTextContains(
      'css',
      'details',
      'Human authority remains in the GitHub UI',
    );
    $this->assertSession()->pageTextContains('View the governed PLAN procedure');
    $this->assertSession()->elementNotExists('css', 'input[type="submit"]');

    $link = $this->getSession()->getPage()->findLink('Prepare PREPROD PLAN');
    self::assertNotNull($link);
    self::assertSame('_blank', $link->getAttribute('target'));
    self::assertSame('noopener noreferrer', $link->getAttribute('rel'));
    $href = $link->getAttribute('href');
    self::assertNotNull($href);
    $parts = parse_url($href);
    self::assertIsArray($parts);
    self::assertSame('https', $parts['scheme'] ?? NULL);
    self::assertSame('github.com', $parts['host'] ?? NULL);
    self::assertSame(
      '/E-merging-digital/agency-website-drupal/issues/new',
      $parts['path'] ?? NULL,
    );
    parse_str($parts['query'] ?? '', $query);
    self::assertSame(
      '[Ops][PLAN] Prepare PREPROD refresh PLAN',
      $query['title'] ?? NULL,
    );
    self::assertSame('Task,P1,status:in-progress', $query['labels'] ?? NULL);
    self::assertSame(
      $this->expectedCockpitPlanIssueBody(),
      $query['body'] ?? NULL,
    );

    $this->drupalGet('/admin/agency/operations/editorial');
    $this->assertSession()->statusCodeEquals(200);
    $this->assertSession()->pageTextContains('overall: BLOCKED');
  }

  /**
   * Proves the cockpit route still rejects POST execution requests.
   */
  public function testPostIsRejectedBecauseNoExecutionRouteExists(): void {
    $account = $this->drupalCreateUser(['access agency operations']);
    $this->drupalLogin($account);

    $driver = $this->getSession()->getDriver();
    self::assertInstanceOf(BrowserKitDriver::class, $driver);
    $client = $driver->getClient();
    $client->followRedirects(FALSE);
    $client->request('POST', $this->baseUrl . '/admin/agency/operations');

    self::assertSame(405, $client->getResponse()->getStatusCode());
  }

  /**
   * Returns the exact human-reviewable issue body generated by the cockpit.
   */
  private function expectedCockpitPlanIssueBody(): string {
    return implode("\n", [
      'Parent: #816',
      '',
      '## Cockpit PREPROD PLAN authority',
      '',
      'This issue authorizes one PLAN against the live main resolved when the issue is opened.',
      '',
      'PLAN = analysis / preparation only',
      'NO DATA MUTATION',
      'APPLY = NOT AUTHORIZED',
      '',
      'AGENCY_PREPROD_COCKPIT_PLAN_AUTHORITY={"authorized_actor":"E-merging-digital","implementation_issue":914,"mode":"PLAN","parent_issue":816,"profile_id":"agency-preprod-refresh-simple-v1","run_attempt":1,"schema_version":1}',
      '',
    ]);
  }

}
