block.settings.emerging_digital_footer_branding:
  type: block_settings
  label: 'Footer branding block settings'
  mapping:
    tagline:
      type: text
      label: 'Tagline'
    legal_name:
      type: label
      label: 'Legal company name'
    company_number:
      type: label
      label: 'Company registration number'
    company_address:
      type: text
      label: 'Company address'
    company_email_label:
      type: label
      label: 'Company public email label'
    company_email:
      type: label
      label: 'Company public email address'
    company_email_uri:
      type: uri
      label: 'Company public email link URI'
    company_phone_label:
      type: label
      label: 'Company public phone label'
    company_phone:
      type: label
      label: 'Company public phone number'
    company_phone_uri:
      type: uri
      label: 'Company public phone link URI'
    status:
      type: boolean
      label: 'Status'
