name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: Quality checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
          tools: composer:v2

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Run PHPCS
        run: vendor/bin/phpcs --standard=phpcs.xml web/modules/custom web/themes/custom web/profiles/custom

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse -c phpstan.neon

      - name: Run Drupal Check
        run: vendor/bin/drupal-check